# Generated by Django 2.2.6 on 2020-01-02 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('size', models.CharField(choices=[('R', 'Regular'), ('S', 'Small'), ('L', 'Large')], default='R', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='pizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Regular', max_length=64, verbose_name='Pizza type')),
            ],
        ),
        migrations.CreateModel(
            name='dinnerPlatter',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
            ],
            bases=('orders.item',),
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ManyToManyField(to='orders.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedDate', models.DateTimeField(blank=True, null=True)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default='False')),
                ('orderItem', models.ManyToManyField(to='orders.orderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users to select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.item', models.Model),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Item')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users to select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizzaType')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.item', models.Model),
        ),
    ]
