# Generated by Django 2.2.6 on 2019-12-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Pizza type')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='Small', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizzaType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingOption', models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options')),
                ('maxToppings', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
