# Generated by Django 2.2.6 on 2019-12-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='maxToppings',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='toppingOption',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='maxToppings',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='toppingOption',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='maxToppings',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='size',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='toppingOption',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='maxToppings',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='size',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='toppingOption',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='toppings',
        ),
    ]
