# Generated by Django 2.2.6 on 2020-01-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatype',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Pizza type'),
        ),
    ]
