# Generated by Django 2.2.6 on 2020-01-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='preselectedToppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping', verbose_name='Pre-selected Toppings'),
        ),
        migrations.AddField(
            model_name='sub',
            name='preselectedToppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping', verbose_name='Pre-selected Toppings'),
        ),
        migrations.AlterField(
            model_name='pizzatype',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Pizza type'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
