# Generated by Django 2.2.6 on 2020-01-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200102_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hasAdditions',
            field=models.ManyToManyField(blank=True, related_name='hasAdditions', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hasToppings',
            field=models.ManyToManyField(blank=True, related_name='hasToppings', to='orders.Topping'),
        ),
    ]
