# Generated by Django 2.2.6 on 2020-01-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200104_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='preselectedToppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping', verbose_name='Pre-selected Toppings'),
        ),
        migrations.AddField(
            model_name='sub',
            name='preselectedToppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping', verbose_name='Pre-selected Toppings'),
        ),
    ]
