# Generated by Django 2.0.3 on 2019-10-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191012_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dinnerPlatters',
            new_name='dinnerPlatter',
        ),
    ]
