# Generated by Django 2.0.3 on 2019-10-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191012_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.ForeignKey(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemSize', to='orders.Size'),
        ),
    ]
