# Generated by Django 2.0.3 on 2019-10-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191013_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='maxToppings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
