# Generated by Django 2.0.3 on 2019-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191013_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='maxToppings',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
