# Generated by Django 2.0.3 on 2019-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191013_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='addToppings',
            field=models.BooleanField(default=False, help_text='Add toppings?'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=64),
        ),
    ]
