# Generated by Django 2.0.3 on 2019-10-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20191013_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='addToppings',
            field=models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1),
        ),
    ]
