# Generated by Django 2.0.3 on 2019-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20191016_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='addToppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='addToppings',
            field=models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1),
        ),
    ]
