# Generated by Django 2.2.6 on 2019-10-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20191016_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='addToppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='maxToppings',
        ),
    ]
