# Generated by Django 2.2.6 on 2019-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20191021_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='maxToppings',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='toppingOption',
            field=models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1),
        ),
        migrations.AddField(
            model_name='sub',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
