# Generated by Django 2.2.6 on 2019-10-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191021_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='maxToppings',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='toppingOption',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='toppings',
        ),
    ]
