# Generated by Django 2.2.6 on 2019-10-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20191021_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppingOption',
            field=models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1),
        ),
    ]
