# Generated by Django 2.2.6 on 2019-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20191029_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='maxToppings',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppingOption',
            field=models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options'),
        ),
        migrations.AlterField(
            model_name='pizzatype',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Pizza type'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='maxToppings',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Max. toppings'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='toppingOption',
            field=models.CharField(choices=[('0', 'No toppings'), ('1', 'Pre-selected'), ('2', 'No more than..'), ('3', 'Select from all'), ('4', 'Additions')], default=('0', 'No toppings'), help_text='Allow users select toppings', max_length=1, verbose_name='Topping Options'),
        ),
    ]
