# Generated by Django 2.2.6 on 2019-11-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20191113_2310'),
        ('orders', '0026_auto_20191103_1613'),
    ]

    operations = [
    ]
