# Generated by Django 2.2.6 on 2019-11-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_merge_20191113_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(default='Small', max_length=64),
        ),
    ]
