# Generated by Django 2.2.6 on 2019-11-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20191112_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large'), ('R', 'Regular')], default='R', max_length=64),
        ),
    ]
