# Generated by Django 2.2.6 on 2019-11-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20191112_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default='Small', on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(default='Small', max_length=64),
        ),
    ]
